- name: Update the Engine on the server
  hosts: uverworld-website
  remote_user: root

  tasks:
  - name: check if cargo is installed
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust

  - name: Install build essentials
    ansible.builtin.apt:
      name: build-essential
      state: present
    become: yes

  - name: Install required packages for Rust compilation
    ansible.builtin.apt:
      name:
        - pkg-config
        - libasound2-dev
        - libssl-dev
        - libudev-dev
      state: present
    become: yes

  - name: Ensure git is installed
    ansible.builtin.package:
      name: git
      state: present
    become: yes

  - name: Copy SSH key from controller to target
    ansible.builtin.copy:
      src: uverworld_server
      dest: /tmp/uverworld_server
      mode: '0600'

  - name: Check if ~/engine is a git repo
    ansible.builtin.stat:
      path: ~/engine/.git
    register: git_repo_check

  - name: Update the repository if ~/engine is already a git repo
    ansible.builtin.git:
      repo: 'git@github.com:Uver-World/server.git'
      dest: ~/engine
      accept_hostkey: yes
      key_file: /tmp/uverworld_server
      update: yes
    when: git_repo_check.stat.exists

  - name: Remove the directory if ~/engine is not a git repo
    ansible.builtin.file:
      path: ~/engine
      state: absent
    when: not git_repo_check.stat.exists

  - name: Clone the repository
    ansible.builtin.git:
      repo: 'git@github.com:Uver-World/server.git'
      dest: ~/engine
      accept_hostkey: yes
      key_file: /tmp/uverworld_server
      force: yes
    when: not git_repo_check.stat.exists

  - name: Remove SSH key from target
    ansible.builtin.file:
      path: /tmp/uverworld_server
      state: absent

  - name: Build the binary
    ansible.builtin.shell:
      cmd: ~/.cargo/bin/cargo build --release
      executable: /bin/bash
      chdir: "~/engine"

  - name: Copy .env file to remote host
    ansible.builtin.copy:
      src: ../.env
      dest: ~/engine/.env
      mode: '0644'

  - name: Run the binary
    ansible.builtin.shell:
      cmd: ./target/release/uverworld
      executable: /bin/bash
      chdir: "~/engine"